package com.rehan.rangoli.domain

/**
 * The symmetry groups the game is built on.
 *
 * The whole game hinges on [orbitOf]: for a given cell it returns every cell
 * that must share the same colour. Because levels are generated by colouring
 * whole orbits at once, every generated pattern is symmetric *by construction* --
 * no solver and no backtracking is ever needed.
 */
enum class SymmetryType(
	val displayName: String,
	val hint: String
) {
	VERTICAL_MIRROR(
		displayName = "Vertical mirror",
		hint = "Left half ka mirror image right side banao"
	),
	HORIZONTAL_MIRROR(
		displayName = "Horizontal mirror",
		hint = "Upar wale half ko neeche mirror karo"
	),
	FOUR_FOLD_REFLECTION(
		displayName = "Four-fold reflection",
		hint = "Ek quadrant diya hai - baaki teen mirror karo"
	),
	ROTATIONAL_90(
		displayName = "90 degree rotation",
		hint = "Mirror nahi - pattern ko 90 degree ghumao"
	),
	DIAGONAL_MIRROR(
		displayName = "Diagonal mirror",
		hint = "Diagonal line ke aar-paar reflect karo"
	),
	EIGHT_FOLD_RADIAL(
		displayName = "Eight-fold radial",
		hint = "Asli rangoli - sirf ek octant diya hai"
	);

	/**
	 * Every cell that must share [cell]'s colour, including [cell] itself.
	 *
	 * Note the odd-grid centre cell is its own only partner, which is exactly
	 * why grids are always odd-sized in this game.
	 */
	fun orbitOf(cell: Cell, size: Int): Set<Cell> {
		val last = size - 1

		val vertical = { c: Cell -> Cell(c.row, last - c.col) }
		val horizontal = { c: Cell -> Cell(last - c.row, c.col) }
		val diagonal = { c: Cell -> Cell(c.col, c.row) }
		val rotate90 = { c: Cell -> Cell(c.col, last - c.row) }

		return when (this) {
			VERTICAL_MIRROR -> setOf(cell, vertical(cell))
			HORIZONTAL_MIRROR -> setOf(cell, horizontal(cell))
			DIAGONAL_MIRROR -> setOf(cell, diagonal(cell))

			FOUR_FOLD_REFLECTION -> setOf(
				cell,
				vertical(cell),
				horizontal(cell),
				horizontal(vertical(cell))
			)

			ROTATIONAL_90 -> {
				var current = cell
				buildSet {
					repeat(4) {
						add(current)
						current = rotate90(current)
					}
				}
			}

			// Dihedral group D4: four rotations, each also reflected.
			EIGHT_FOLD_RADIAL -> {
				var current = cell
				buildSet {
					repeat(4) {
						add(current)
						add(diagonal(current))
						current = rotate90(current)
					}
				}
			}
		}
	}

	/**
	 * The region shown to the player as a starting clue.
	 *
	 * Guaranteed to contain at least one member of every orbit, so the rest of
	 * the board is always logically deducible.
	 */
	fun fundamentalDomain(size: Int): Set<Cell> {
		val mid = (size - 1) / 2
		val cells = mutableSetOf<Cell>()

		for (row in 0 until size) {
			for (col in 0 until size) {
				val keep = when (this) {
					VERTICAL_MIRROR -> col <= mid
					HORIZONTAL_MIRROR -> row <= mid
					FOUR_FOLD_REFLECTION -> row <= mid && col <= mid
					ROTATIONAL_90 -> row <= mid && col <= mid
					DIAGONAL_MIRROR -> col <= row
					EIGHT_FOLD_RADIAL -> row <= mid && col <= row
				}
				if (keep) cells += Cell(row, col)
			}
		}
		return cells
	}
}
